# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    # 设置UTF-8编码
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  # 应用名称
  application:
    name: web-application
  servlet:
    multipart:
      # 设置单个文件大小
      max-file-size: 50MB
      # 设置单次请求文件的总大小
      max-request-size: 50MB
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    # 开启模板缓存（默认值： true ）
    cache: true
    # 检查模板是否存在，然后再呈现
    check-template: true
    # 检查模板位置是否正确（默认值 :true ）
    check-template-location: true
    # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    enabled: true
    # 模板编码
    encoding: UTF-8
    # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    prefix: classpath:/templates/
    # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
    suffix: .html

